### ISSUE TITLE
B2 backups

### ISSUE THREAD

**Issue by NurvX** [arthurgeek/vaultwarden-fly-template#21]
Hi there, 

I have configured using B2 backups, I can see the backups happening in the logs but not seeing anything getting through to B2.

Is anyway I could troubloshoot this ? 
Only change in .config.env is I have added below variables instead of default s3. 

B2_ACCOUNT_ID=
B2_ACCOUNT_KEY=

**Comment by arthurgeek** [comment]
Hey! If you SSH into your fly machine and run `overmind connect backup`  does it show anything different? Do you get any emails about failed backup? If so, can you please post their contents here?

You can also try running backup manually inside your machine with `/scripts/restic-backup.sh` or running `restic` commands yourself, it might give us some extra clues.

From what I can see from [b2 docs](https://www.backblaze.com/docs/cloud-storage-integrate-restic-with-backblaze-b2), perhaps you'll need to also change `RESTIC_REPOSITORY`.

Let me know if any of that helps out.

**Comment by NurvX** [comment]
sorry i wasnt able to find where your script was connecting to B2 or S3 so I wrote my own little script to get it working.
Thanks for maintaining this repo, cheers.
```
#!/bin/bash

DATE=$(date +"%Y-%m-%d_%H-%M")
ARCHIVE_FILE="$DATE.tar.gz"
B2_BUCKET_NAME=“xxxxxxx”
B2_ACCOUNT_ID=“xxxxxxxxx”
B2_ACCOUNT_KEY=“xxxxxxx”

# Install necessary packages (assuming b2 is already installed)
apt-get update
apt-get install -y b2

# Create the archive
tar -czf "$ARCHIVE_FILE" data

# Upload the archive to Backblaze B2 bucket
./b2 authorize_account "$B2_ACCOUNT_ID" "$B2_ACCOUNT_KEY"
./b2 upload_file "$B2_BUCKET_NAME" "$ARCHIVE_FILE" "$ARCHIVE_FILE"

# Clean up the local archive file
rm "$ARCHIVE_FILE"
```

**Comment by arthurgeek** [comment]
The backup script uses [restic](https://restic.net/)  to connect to any backup source, B2 being one of them. I use this method so users are free to use any source supported by restock, but also because restic maintains an encrypted, incremental backup and makes everything really easy to restore. The script also [removes old backups automatically](https://github.com/arthurgeek/vaultwarden-fly-template/blob/main/scripts/restic-backup.sh#L95) and notifies via email in case of error.

You can check how to connect restic to b2 here: https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2.

You don't need to backup the whole data folder, you can just backup the SQLite database, but I recommend you use SQLite to create that backup instead of backing up the .sqlite file directly, as it can lead to database corruption if two files access the same file without a lock. My script does this here: https://github.com/arthurgeek/vaultwarden-fly-template/blob/main/scripts/restic-backup.sh#L82-L84.

But, I suggest you use restic anyway, as I said, you likely just need to change `RESTIC_REPOSITORY` to include `b2:` in front of it. I don't use B2 myself, so can't confirm, but should most likely work without any issues.

**Comment by arthurgeek** [comment]
@NurvX I'm closing this as solved. Please reopen if it's still not working.
